codecov:
  require_ci_to_pass: yes
  ci:
    - "travis.org"

coverage:
  precision: 2
  round: down
  range: "100...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
 - "src/tests"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no